### ISSUE TITLE
DX213 not working on DS723+ after update

### ISSUE THREAD

**Issue by 0nl0gisch** [007revad/Synology_enable_eunit#50]
Hello,

I have been using your script for a while now with lots of pleasure on my DS723+ and DX213. So i can also confirm for you that your script is working on a DS723+ with a DX213.

Unfortunately, after updating to DSM version: 7.2.2-72806, i can not get it working anymore. 

It gives a message that it found an incompatible expansion unit and that i need to replace it with a compatible one. This was also before i first started using your script.

I am using your script as a triggered task and it was working fine on DSM version: 7.2.1-69057 Update 5.

I have already deleted the task and made a new one but it doesn't help.

I hope you have a solution for me.

Kind regards.

PS. i am not a programmer so please forgive me if i don't understand all. Also the system language is in dutch on the screenshots ;-)

![image](https://github.com/user-attachments/assets/dda25ebb-4f65-447c-950f-4ac61ad01cc8)

![image](https://github.com/user-attachments/assets/bd5b4724-2447-4edc-a47f-3c58fca0a187)

![image](https://github.com/user-attachments/assets/f44f5c57-199a-4951-9ddc-712387c731db)

![image](https://github.com/user-attachments/assets/0641eb14-42f2-48c0-ac3e-03a96392c1eb)

![image](https://github.com/user-attachments/assets/3a9435ff-c717-4f05-a83a-036db567ade7)

**Comment by 007revad** [comment]
After updating DSM you need to run the script then reboot.

**Comment by 0nl0gisch** [comment]
Thanks for your message.

I thought that i have already tested that but not sure.

I'll let you know.

**Comment by 0nl0gisch** [comment]
I have tried your solution but still it's not working.

Any other suggestions?

**Comment by 0nl0gisch** [comment]
I still can't get it working.

Could it have something to do with the last DSM update?

Richard

**Comment by 0nl0gisch** [comment]
So as a noob i started to work with terminal commands via putty and now i got it working. Still a huge thank you for this script so i can use the expansion unit on my DS723+. 

Should have supported you earlier but better late than never:-)
